services:
  - type: web
    name: worksphere-backend
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npx prisma migrate deploy && node -r tsconfig-paths/register dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: worksphere-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://ems-work-sphere.vercel.app
      - key: CORS_ORIGINS
        value: https://ems-work-sphere.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: noreply@worksphere.com

databases:
  - name: worksphere-db
    databaseName: ems_db
    user: ems_user
